# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd382009f7bcc7842b889bbd9859cffa68414d345ea696b4487bf58ed1c5f772cda6ae562504e58f6f3f0c42d4f6bc2c891ebbf02ff00ac35a8bd690ae50a539

test:
  secret_key_base: b87032421d994c662a5a0ede2c90a7913ece149001151462d37175892efae6c6bb7baec48b247accb34f4464ed29ccc32bc6170076202bec2e2222a601f1c751

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
